default:
  interruptible: true

.script:
  script:
    - |
      julia --project=@. -e "
        using Pkg
        Pkg.build()
        Pkg.test(coverage=${COVERAGE-false})"

.rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /doc/
      when: never
    - when: always

test:
  parallel:
    matrix:
      - IMAGE:
          - julia:1.6
          - julia:1.7
          - julia:1.8
          - julia:1.9
  image: $IMAGE
  variables:
    COVERAGE: "true"
  extends:
    - .script
    - .rules
  artifacts:
    when: always
    name: artifact-$IMAGE
    paths:
      - "**/*.cov"

coverage:
  image: julia:1.6
  needs:
    - test
  extends:
    - .rules
  coverage: /Test coverage (\d+\.\d+%)/
  script:
    - |
      julia --project=@. -e '
      using Pkg
      Pkg.add("LocalCoverage")
      using LocalCoverage
      c = generate_coverage(; run_test=false)
      # Print overview
      using Printf
      @printf "Test coverage %.2f%%\n" c.coverage_percentage
      # Generate detailed report for GitLab
      using LocalCoverage: COVDIR, LCOVINFO
      cobertura = joinpath(COVDIR, "cobertura.xml")
      lcov = joinpath(COVDIR, LCOVINFO)
      write_lcov_to_xml(cobertura, lcov)
      '
  artifacts:
    paths:
      - coverage/lcov.info
      - coverage/cobertura.xml
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura.xml
