include:
  - component: $CI_SERVER_FQDN/ci-components/julia/cache@1
  - component: $CI_SERVER_FQDN/ci-components/julia/runtests@1

default:
  interruptible: true

# Prevent duplicate pipelines
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

benchmark:
  image: julia:1.10
  cache:
    - !reference [.julia_cache, cache]
    - key: tune#${CI_RUNNER_ID}
      paths:
        - benchmark/tune.json
  script:
    - julia -e 'import Pkg; Pkg.add(["BenchmarkTools", "MORWiki", "PkgBenchmark"])'
    - julia --project=@. -e 'import Pkg; Pkg.instantiate()'
    - julia --project=@. -e 'import DifferentialRiccatiEquations as DRE; using PkgBenchmark; data = benchmarkpkg(DRE); export_markdown("report.md", data)'
  artifacts:
    paths:
      - "report.md"

