default:
  interruptible: true

.script:
  script:
    - |
      julia --project=@. -e "
        using Pkg
        Pkg.build()
        Pkg.test(coverage=${COVERAGE-false})"
  rules:
    - if: $CI_COMMIT_BRANCH =~ /doc/
      when: never
    - when: always

.coverage:
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        c, t = get_summary(process_folder())
        using Printf
        @printf "Test coverage %.2f%%\n" 100c / t'

test:
  parallel:
    matrix:
      - IMAGE:
          - julia:1.7
          - julia:1.8
          - julia:1.9
  image: $IMAGE
  extends:
    - .script


test-coverage:
  image: julia:1.6
  variables:
    COVERAGE: "true"
  extends:
    - .script
    - .coverage
