name = "DifferentialRiccatiEquations"
uuid = "9819f967-4574-4d9d-b214-002eeba273d9"
authors = ["Jonas Schulze <jschulze@mpi-magdeburg.mpg.de> and contributors"]
version = "0.1.0"

[deps]
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
